#!/usr/local/bin/ruby
$:.unshift File.dirname(__FILE__)
require 'Directory.rb'
require 'DirRepository.rb'
require 'Command.rb'
require 'CommandParser.rb'
require 'fileutils'
require 'json'
class Main
    def initialize
        pa=__FILE__.split("/")
        pa.pop
        json_path =pa.join("/")+'/data.json'
        json_data=open(json_path) do |io|
            JSON.load(io)
        end
        # @json_data = json_data
        # @json_path = json_path
        commandparser= CommandParser.new(ARGV)
        command= commandparser.parse
        if command.type == 'generate' || command.type == "g" then
            # 親ディレクトリの作成
            repo_dir= DirRepository.new(command.dir_name)
            repo_dir.make
            json_data.store(Dir.pwd+'/'+command.dir_name,Array.new(command.max))
            # 子ディレクトリの生成
            num= (0..command.max-1).to_a
            dir= Array.new(command.max)
            num.map{ |n|
                str= (n+1).to_s
                while true do
                    if str.length <command.format then
                        str= "0"+str
                    else break
                    end
                end
                dir[n]= Directory.new(command.dir_name + "/" + command.header + str)
                dir[n].make
                json_data[Dir.pwd+"/"+command.dir_name][n]= command.header+str
            }
        elsif command.type == 'submit' || command.type == "s" then
            cnt=0
            total=0
            cwd= Dir.pwd
            if json_data.has_key?(Dir.pwd+'/'+command.dir_name) then
                puts '提出状況だよっ！'
                json_data[Dir.pwd+'/'+command.dir_name].map{ |n|
                    Dir.chdir(cwd)
                    Dir.chdir(command.dir_name + '/' + n)
                    if Dir.glob("*").length == 0 then 
                        puts "[x]"+n
                        total+=1
                    else
                        puts "[o]"+n
                        cnt+=1
                        total+=1
                    end
                }
                puts '提出率は、('+cnt.to_s+'/'+total.to_s+')'
                # puts json_data[Dir.pwd+"/"+command.dir_name].class
                puts 'でも、実際は提出コマンド打って提出したのかどうかわからないから、ファイルが存在しているディレクトリはすぐに提出しようね！'
                puts 'あれ、、、提出コマンド知らない...？'
                puts '隣の人にでも聞いたらどうかなっ！'
            else
                puts 'そんなフォルダ作ってないよ！'
                puts '私が作成したフォルダ以外の面倒なんて見きれないわ！'
            end
            Dir.chdir(cwd)
        elsif command.type == 'list' || command.type == "l"then
            puts '今まで私が作成したフォルダ一覧だよ！'
            puts '言わずもがなだけど、削除する際にはdelete命令で削除してね！'
            json_data.keys.map{|n| puts n}
        elsif command.type == 'delete' || command.type == "d" then
            if json_data.has_key?(Dir.pwd+'/'+command.dir_name) then
                puts '本当に削除していいの？？？(y/n)'
                temp= STDIN.gets
                temp.chomp!
                if temp == 'y' then
                    # 削除
                    FileUtils.rm_rf(Dir.pwd+'/'+command.dir_name)
                    json_data.delete(Dir.pwd+'/'+command.dir_name)
                    puts '削除完了！'
                else 
                    puts '消しませんでしたよ！'
                end
            else
                puts 'そんなディレクトリ管理してませんっ！'
                puts '私が作成したディレクトリ消したかったら対象ディレクトリがあるディレクトリまで移動してよね！'
            end
        else
            puts 'なんか知らないけど引数違うよ!'
            puts ' generate [親ディレクトリ名] -h [ヘッダ文字] -f [何桁表示か] -m [子ディレクトリの個数]'
            puts ' submit [ディレクトリ名]'
            puts ' list'
            puts ' delete [ディレクトリ名]'
            puts 'のうちどれか選んでね！'
            puts '意味はその命令通りだよ！'
        end
        # json 書き込み
        open(json_path, 'w') do |io|
            JSON.dump(json_data, io)
        end
    end
end
Main.new
